version: '3.8'

services:
  voloscodex-api:
    image: voloscodex-api
    build:
      context: .
      dockerfile: VolosCodex.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis:ConnectionString=redis:6379
      - Gemini:ApiKey=${GEMINI_API_KEY}
    volumes:
      - ./VolosCodex.Domain/Books:/app/Books
      - embeddings_model_cache:/app/LocalEmbeddingsModel
    depends_on:
      - redis

  voloscodex-front:
    image: voloscodex-front
    build:
      context: ./volos-codex-front-react
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - voloscodex-api

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  embeddings_model_cache:
